version: "3"
services:
  tgbot:
    restart: always
    image: hackroid/tg-dumb-bot
    environment:
      - token=${token}
      - debug=${debug}
    volumes:
      - /etc/localtime:/etc/localtime:ro
#    depends_on:
#      - another_service
#  another_service:
#    restart: always
#    image: hackroid/another_image