inputs:
  DOCKERHUB_USERNAME:
    description: "DOCKERHUB_USERNAME"
    required: true
  DOCKERHUB_TOKEN:
    description: "DOCKERHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Build and push tgbot_Docker_image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./tgbotDockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: hackroid/tg-dumb-bot:latest, hackroid/tg-dumb-bot:${{ github.ref_name }}

#    - name: Build and push another_image
#      id: docker_build
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: ./another_image
#        platforms: linux/amd64,linux/arm64
#        push: true
#        tags: hackroid/another:latest, hackroid/another:${{ github.ref_name }}